# Generated by Django 4.0 on 2021-12-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='session',
            field=models.TextField(),
        ),
    ]
