# Generated by Django 4.0 on 2021-12-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_document_df'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='df',
            field=models.JSONField(),
        ),
    ]
