# Generated by Django 4.0 on 2021-12-27 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_document_df'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='df',
        ),
    ]
