# Generated by Django 4.0 on 2021-12-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_document_df'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='df',
            field=models.JSONField(null=True),
        ),
    ]
