# Generated by Django 4.0 on 2021-12-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_document_df'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='config',
            field=models.JSONField(null=True),
        ),
    ]
