# Generated by Django 4.0 on 2021-12-28 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_document_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='df',
        ),
    ]
