# Generated by Django 4.0 on 2021-12-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_document_df'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='params',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
